from PyQt5 import QtCore, QtGui, QtWidgets

# Line 372,373,386,387 modified

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(800, 480)  # 800 480
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Configuration.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Configuration)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_4 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 5, 2, 1, 1)
        self.Password_8 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_8.setFont(font)
        self.Password_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_8.setObjectName("Password_8")
        self.gridLayout.addWidget(self.Password_8, 9, 4, 1, 1)
        self.RPi_5 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_5.setFont(font)
        self.RPi_5.setObjectName("RPi_5")
        self.gridLayout.addWidget(self.RPi_5, 6, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 4, 2, 1, 1)
        self.RPi = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.RPi.setFont(font)
        self.RPi.setObjectName("RPi")
        self.gridLayout.addWidget(self.RPi, 0, 0, 1, 1)
        self.RPi_4 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_4.setFont(font)
        self.RPi_4.setObjectName("RPi_4")
        self.gridLayout.addWidget(self.RPi_4, 5, 0, 1, 1)
        self.SSID_4 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_4.setFont(font)
        self.SSID_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_4.setObjectName("SSID_4")
        self.gridLayout.addWidget(self.SSID_4, 5, 1, 1, 1)
        self.SSID_5 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_5.setFont(font)
        self.SSID_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_5.setObjectName("SSID_5")
        self.gridLayout.addWidget(self.SSID_5, 6, 1, 1, 1)
        self.Password_6 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_6.setFont(font)
        self.Password_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_6.setObjectName("Password_6")
        self.gridLayout.addWidget(self.Password_6, 7, 4, 1, 1)
        self.Password_5 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_5.setFont(font)
        self.Password_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_5.setObjectName("Password_5")
        self.gridLayout.addWidget(self.Password_5, 6, 4, 1, 1)
        self.SSID_1 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_1.setFont(font)
        self.SSID_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_1.setObjectName("SSID_1")
        self.gridLayout.addWidget(self.SSID_1, 2, 1, 1, 1)
        self.RPi_2 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_2.setFont(font)
        self.RPi_2.setObjectName("RPi_2")
        self.gridLayout.addWidget(self.RPi_2, 3, 0, 1, 1)
        self.RPi_1 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_1.setFont(font)
        self.RPi_1.setObjectName("RPi_1")
        self.gridLayout.addWidget(self.RPi_1, 2, 0, 1, 1)
        self.SSID_2 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_2.setFont(font)
        self.SSID_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_2.setObjectName("SSID_2")
        self.gridLayout.addWidget(self.SSID_2, 3, 1, 1, 1)
        self.SSID_0 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_0.setFont(font)
        self.SSID_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_0.setObjectName("SSID_0")
        self.gridLayout.addWidget(self.SSID_0, 1, 1, 1, 1)
        self.RPi_3 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_3.setFont(font)
        self.RPi_3.setObjectName("RPi_3")
        self.gridLayout.addWidget(self.RPi_3, 4, 0, 1, 1)
        self.Password_7 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_7.setFont(font)
        self.Password_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_7.setObjectName("Password_7")
        self.gridLayout.addWidget(self.Password_7, 8, 4, 1, 1)
        self.SSID_7 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_7.setFont(font)
        self.SSID_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_7.setObjectName("SSID_7")
        self.gridLayout.addWidget(self.SSID_7, 8, 1, 1, 1)
        self.SSID = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.SSID.setFont(font)
        self.SSID.setObjectName("SSID")
        self.gridLayout.addWidget(self.SSID, 0, 1, 1, 2)
        self.spinBox_7 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 8, 2, 1, 1)
        self.spinBox_0 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_0.setFont(font)
        self.spinBox_0.setObjectName("spinBox_0")
        self.gridLayout.addWidget(self.spinBox_0, 1, 2, 1, 1)
        self.SSID_3 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_3.setFont(font)
        self.SSID_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_3.setObjectName("SSID_3")
        self.gridLayout.addWidget(self.SSID_3, 4, 1, 1, 1)
        self.RPi_8 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_8.setFont(font)
        self.RPi_8.setObjectName("RPi_8")
        self.gridLayout.addWidget(self.RPi_8, 9, 0, 1, 1)
        self.SSID_6 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_6.setFont(font)
        self.SSID_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_6.setObjectName("SSID_6")
        self.gridLayout.addWidget(self.SSID_6, 7, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 7, 2, 1, 1)
        self.RPi_0 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_0.setFont(font)
        self.RPi_0.setObjectName("RPi_0")
        self.gridLayout.addWidget(self.RPi_0, 1, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 6, 2, 1, 1)
        self.Password = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.Password.setFont(font)
        self.Password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password.setObjectName("Password")
        self.gridLayout.addWidget(self.Password, 0, 4, 1, 1)
        self.SSID_8 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.SSID_8.setFont(font)
        self.SSID_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SSID_8.setObjectName("SSID_8")
        self.gridLayout.addWidget(self.SSID_8, 9, 1, 1, 1)
        self.Password_3 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_3.setFont(font)
        self.Password_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_3.setObjectName("Password_3")
        self.gridLayout.addWidget(self.Password_3, 4, 4, 1, 1)
        self.RPi_6 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_6.setFont(font)
        self.RPi_6.setObjectName("RPi_6")
        self.gridLayout.addWidget(self.RPi_6, 7, 0, 1, 1)
        self.Password_0 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_0.setFont(font)
        self.Password_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_0.setObjectName("Password_0")
        self.gridLayout.addWidget(self.Password_0, 1, 4, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 3, 2, 1, 1)
        self.Password_2 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_2.setFont(font)
        self.Password_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_2.setObjectName("Password_2")
        self.gridLayout.addWidget(self.Password_2, 3, 4, 1, 1)
        self.RPi_7 = QtWidgets.QLabel(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RPi_7.setFont(font)
        self.RPi_7.setObjectName("RPi_7")
        self.gridLayout.addWidget(self.RPi_7, 8, 0, 1, 1)
        self.Password_1 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_1.setFont(font)
        self.Password_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_1.setObjectName("Password_1")
        self.gridLayout.addWidget(self.Password_1, 2, 4, 1, 1)
        self.Password_4 = QtWidgets.QLineEdit(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_4.setFont(font)
        self.Password_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Password_4.setObjectName("Password_4")
        self.gridLayout.addWidget(self.Password_4, 5, 4, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 9, 2, 1, 1)
        self.spinBox_1 = QtWidgets.QSpinBox(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_1.setFont(font)
        self.spinBox_1.setObjectName("spinBox_1")
        self.gridLayout.addWidget(self.spinBox_1, 2, 2, 1, 1)
        self.spacer = QtWidgets.QLabel(Configuration)
        self.spacer.setText("")
        self.spacer.setObjectName("spacer")
        self.gridLayout.addWidget(self.spacer, 1, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Ok = QtWidgets.QPushButton(Configuration)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Ok.setFont(font)
        QtWidgets.QToolTip.setFont(font)                                                    # modified by me
        self.Ok.setToolTip("Save the modified configuration file into the U-Disk")          # modified by me
        self.Ok.setStatusTip("")
        self.Ok.setWhatsThis("")
        self.Ok.setAccessibleName("")
        self.Ok.setAccessibleDescription("")
        self.Ok.setObjectName("Ok")
        self.horizontalLayout.addWidget(self.Ok)
        self.Cancel = QtWidgets.QPushButton(Configuration)
        self.Cancel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Cancel.setFont(font)
        # QtWidgets.QToolTip.setFont(font)                                                    # modified by me
        self.Cancel.setToolTip("Save the default configuration file into the U-Disk")       # modified by me
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 2, 1, 1)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "Configuration"))
        self.Password_8.setText(_translate("Configuration", "12345678"))
        self.RPi_5.setText(_translate("Configuration", "5.slave_RPi:"))
        self.RPi.setText(_translate("Configuration", "RPi"))
        self.RPi_4.setText(_translate("Configuration", "4.slave_RPi:"))
        self.SSID_4.setText(_translate("Configuration", "4.slave_RPi_"))
        self.SSID_5.setText(_translate("Configuration", "5.slave_RPi_"))
        self.Password_6.setText(_translate("Configuration", "12345678"))
        self.Password_5.setText(_translate("Configuration", "12345678"))
        self.SSID_1.setText(_translate("Configuration", "1.slave_RPi_"))
        self.RPi_2.setText(_translate("Configuration", "2.slave_RPi:"))
        self.RPi_1.setText(_translate("Configuration", "1.slave_RPi:"))
        self.SSID_2.setText(_translate("Configuration", "2.slave_RPi_"))
        self.SSID_0.setText(_translate("Configuration", "master_RPi_"))
        self.RPi_3.setText(_translate("Configuration", "3.slave_RPi:"))
        self.Password_7.setText(_translate("Configuration", "12345678"))
        self.SSID_7.setText(_translate("Configuration", "7.slave_RPi_"))
        self.SSID.setText(_translate("Configuration", "SSID"))
        self.SSID_3.setText(_translate("Configuration", "3.slave_RPi_"))
        self.RPi_8.setText(_translate("Configuration", "8.slave_RPi:"))
        self.SSID_6.setText(_translate("Configuration", "6.slave_RPi_"))
        self.RPi_0.setText(_translate("Configuration", "master_RPi:"))
        self.Password.setText(_translate("Configuration", "Password"))
        self.SSID_8.setText(_translate("Configuration", "8.slave_RPi_"))
        self.Password_3.setText(_translate("Configuration", "12345678"))
        self.RPi_6.setText(_translate("Configuration", "6.slave_RPi:"))
        self.Password_0.setText(_translate("Configuration", "12345678"))
        self.Password_2.setText(_translate("Configuration", "12345678"))
        self.RPi_7.setText(_translate("Configuration", "7.slave_RPi:"))
        self.Password_1.setText(_translate("Configuration", "12345678"))
        self.Password_4.setText(_translate("Configuration", "12345678"))
        self.Ok.setText(_translate("Configuration", "Ok"))
        self.Cancel.setText(_translate("Configuration", "Cancel"))

