# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataShow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1488, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.gridLayout.addWidget(self.lcdNumber_17, 3, 8, 1, 1)
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.gridLayout.addWidget(self.lcdNumber_21, 3, 16, 1, 1)
        self.salve_RPi1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi1.sizePolicy().hasHeightForWidth())
        self.salve_RPi1.setSizePolicy(sizePolicy)
        self.salve_RPi1.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.salve_RPi1.setFont(font)
        self.salve_RPi1.setObjectName("salve_RPi1")
        self.gridLayout.addWidget(self.salve_RPi1, 2, 0, 1, 1)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout.addWidget(self.lcdNumber_7, 2, 14, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 11, 10, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 0, 21, 10, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 13, 9, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 15, 9, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 10, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 1, 9, 9, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 1, 19, 9, 1)
        self.lcdNumber_30 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.gridLayout.addWidget(self.lcdNumber_30, 4, 8, 1, 1)
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.gridLayout.addWidget(self.lcdNumber_29, 4, 6, 1, 1)
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.gridLayout.addWidget(self.lcdNumber_28, 4, 4, 1, 1)
        self.lcdNumber_36 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_36.setObjectName("lcdNumber_36")
        self.gridLayout.addWidget(self.lcdNumber_36, 4, 20, 1, 1)
        self.lcdNumber_32 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.gridLayout.addWidget(self.lcdNumber_32, 4, 12, 1, 1)
        self.lcdNumber_31 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.gridLayout.addWidget(self.lcdNumber_31, 4, 10, 1, 1)
        self.Luftdrucksensor4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Luftdrucksensor4.setFont(font)
        self.Luftdrucksensor4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Luftdrucksensor4.setObjectName("Luftdrucksensor4")
        self.gridLayout.addWidget(self.Luftdrucksensor4, 1, 8, 1, 1)
        self.Luftdruck = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Luftdruck.setFont(font)
        self.Luftdruck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Luftdruck.setAlignment(QtCore.Qt.AlignCenter)
        self.Luftdruck.setObjectName("Luftdruck")
        self.gridLayout.addWidget(self.Luftdruck, 0, 2, 1, 9)
        self.Temperatur = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Temperatur.setFont(font)
        self.Temperatur.setAlignment(QtCore.Qt.AlignCenter)
        self.Temperatur.setObjectName("Temperatur")
        self.gridLayout.addWidget(self.Temperatur, 0, 12, 1, 9)
        self.salve_RPi8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi8.sizePolicy().hasHeightForWidth())
        self.salve_RPi8.setSizePolicy(sizePolicy)
        self.salve_RPi8.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi8.setFont(font)
        self.salve_RPi8.setObjectName("salve_RPi8")
        self.gridLayout.addWidget(self.salve_RPi8, 9, 0, 1, 1)
        self.salve_RPi6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi6.sizePolicy().hasHeightForWidth())
        self.salve_RPi6.setSizePolicy(sizePolicy)
        self.salve_RPi6.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi6.setFont(font)
        self.salve_RPi6.setObjectName("salve_RPi6")
        self.gridLayout.addWidget(self.salve_RPi6, 7, 0, 1, 1)
        self.salve_RPi4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi4.sizePolicy().hasHeightForWidth())
        self.salve_RPi4.setSizePolicy(sizePolicy)
        self.salve_RPi4.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi4.setFont(font)
        self.salve_RPi4.setObjectName("salve_RPi4")
        self.gridLayout.addWidget(self.salve_RPi4, 5, 0, 1, 1)
        self.salve_RPi2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi2.sizePolicy().hasHeightForWidth())
        self.salve_RPi2.setSizePolicy(sizePolicy)
        self.salve_RPi2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi2.setFont(font)
        self.salve_RPi2.setObjectName("salve_RPi2")
        self.gridLayout.addWidget(self.salve_RPi2, 3, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 4, 1, 1)
        self.salve_RPi7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi7.sizePolicy().hasHeightForWidth())
        self.salve_RPi7.setSizePolicy(sizePolicy)
        self.salve_RPi7.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi7.setFont(font)
        self.salve_RPi7.setObjectName("salve_RPi7")
        self.gridLayout.addWidget(self.salve_RPi7, 8, 0, 1, 1)
        self.Luftdrucksensor5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Luftdrucksensor5.setFont(font)
        self.Luftdrucksensor5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Luftdrucksensor5.setObjectName("Luftdrucksensor5")
        self.gridLayout.addWidget(self.Luftdrucksensor5, 1, 10, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout.addWidget(self.lcdNumber_5, 2, 10, 1, 1)
        self.Luftdrucksensor1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Luftdrucksensor1.setFont(font)
        self.Luftdrucksensor1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Luftdrucksensor1.setObjectName("Luftdrucksensor1")
        self.gridLayout.addWidget(self.Luftdrucksensor1, 1, 2, 1, 1)
        self.Temperatursensor3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperatursensor3.setFont(font)
        self.Temperatursensor3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Temperatursensor3.setObjectName("Temperatursensor3")
        self.gridLayout.addWidget(self.Temperatursensor3, 1, 16, 1, 1)
        self.Temperatursensor2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperatursensor2.setFont(font)
        self.Temperatursensor2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Temperatursensor2.setObjectName("Temperatursensor2")
        self.gridLayout.addWidget(self.Temperatursensor2, 1, 14, 1, 1)
        self.Temperatursensor4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperatursensor4.setFont(font)
        self.Temperatursensor4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Temperatursensor4.setObjectName("Temperatursensor4")
        self.gridLayout.addWidget(self.Temperatursensor4, 1, 18, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 2, 6, 1, 1)
        self.lcdNumber_1 = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_1.setFont(font)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.gridLayout.addWidget(self.lcdNumber_1, 2, 2, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 2, 8, 1, 1)
        self.salve_RPi5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi5.sizePolicy().hasHeightForWidth())
        self.salve_RPi5.setSizePolicy(sizePolicy)
        self.salve_RPi5.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi5.setFont(font)
        self.salve_RPi5.setObjectName("salve_RPi5")
        self.gridLayout.addWidget(self.salve_RPi5, 6, 0, 1, 1)
        self.Temperatursensor5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperatursensor5.setFont(font)
        self.Temperatursensor5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Temperatursensor5.setObjectName("Temperatursensor5")
        self.gridLayout.addWidget(self.Temperatursensor5, 1, 20, 1, 1)
        self.salve_RPi3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salve_RPi3.sizePolicy().hasHeightForWidth())
        self.salve_RPi3.setSizePolicy(sizePolicy)
        self.salve_RPi3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.salve_RPi3.setFont(font)
        self.salve_RPi3.setObjectName("salve_RPi3")
        self.gridLayout.addWidget(self.salve_RPi3, 4, 0, 1, 1)
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.gridLayout.addWidget(self.lcdNumber_14, 3, 2, 1, 1)
        self.lcdNumber_37 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_37.setObjectName("lcdNumber_37")
        self.gridLayout.addWidget(self.lcdNumber_37, 4, 22, 1, 1)
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.gridLayout.addWidget(self.lcdNumber_16, 3, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 7, 9, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 5, 9, 1)
        self.Beschleunigung = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Beschleunigung.setFont(font)
        self.Beschleunigung.setAlignment(QtCore.Qt.AlignCenter)
        self.Beschleunigung.setObjectName("Beschleunigung")
        self.gridLayout.addWidget(self.Beschleunigung, 0, 22, 1, 3)
        self.Luftdrucksensor2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Luftdrucksensor2.setFont(font)
        self.Luftdrucksensor2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Luftdrucksensor2.setObjectName("Luftdrucksensor2")
        self.gridLayout.addWidget(self.Luftdrucksensor2, 1, 4, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 17, 9, 1)
        self.Luftdrucksensor3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Luftdrucksensor3.setFont(font)
        self.Luftdrucksensor3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Luftdrucksensor3.setObjectName("Luftdrucksensor3")
        self.gridLayout.addWidget(self.Luftdrucksensor3, 1, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 3, 9, 1)
        self.Temperatursensor1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperatursensor1.setFont(font)
        self.Temperatursensor1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Temperatursensor1.setObjectName("Temperatursensor1")
        self.gridLayout.addWidget(self.Temperatursensor1, 1, 12, 1, 1)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout.addWidget(self.lcdNumber_10, 2, 20, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout.addWidget(self.lcdNumber_8, 2, 16, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout.addWidget(self.lcdNumber_9, 2, 18, 1, 1)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.gridLayout.addWidget(self.lcdNumber_11, 2, 22, 1, 1)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.gridLayout.addWidget(self.lcdNumber_6, 2, 12, 1, 1)
        self.lcdNumber_35 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_35.setObjectName("lcdNumber_35")
        self.gridLayout.addWidget(self.lcdNumber_35, 4, 18, 1, 1)
        self.lcdNumber_27 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_27.setObjectName("lcdNumber_27")
        self.gridLayout.addWidget(self.lcdNumber_27, 4, 2, 1, 1)
        self.lcdNumber_26 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.gridLayout.addWidget(self.lcdNumber_26, 3, 24, 1, 1)
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.gridLayout.addWidget(self.lcdNumber_13, 2, 24, 1, 1)
        self.lcdNumber_33 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_33.setObjectName("lcdNumber_33")
        self.gridLayout.addWidget(self.lcdNumber_33, 4, 14, 1, 1)
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.gridLayout.addWidget(self.lcdNumber_18, 3, 10, 1, 1)
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.gridLayout.addWidget(self.lcdNumber_22, 3, 18, 1, 1)
        self.lcdNumber_38 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_38.setObjectName("lcdNumber_38")
        self.gridLayout.addWidget(self.lcdNumber_38, 4, 23, 1, 1)
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.gridLayout.addWidget(self.lcdNumber_20, 3, 14, 1, 1)
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.gridLayout.addWidget(self.lcdNumber_12, 2, 23, 1, 1)
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.gridLayout.addWidget(self.lcdNumber_23, 3, 20, 1, 1)
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.gridLayout.addWidget(self.lcdNumber_19, 3, 12, 1, 1)
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.gridLayout.addWidget(self.lcdNumber_24, 3, 22, 1, 1)
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.gridLayout.addWidget(self.lcdNumber_15, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 23, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 22, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 24, 1, 1)
        self.lcdNumber_34 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_34.setObjectName("lcdNumber_34")
        self.gridLayout.addWidget(self.lcdNumber_34, 4, 16, 1, 1)
        self.lcdNumber_25 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.gridLayout.addWidget(self.lcdNumber_25, 3, 23, 1, 1)
        self.lcdNumber_42 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_42.setObjectName("lcdNumber_42")
        self.gridLayout.addWidget(self.lcdNumber_42, 5, 6, 1, 1)
        self.lcdNumber_41 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_41.setObjectName("lcdNumber_41")
        self.gridLayout.addWidget(self.lcdNumber_41, 5, 4, 1, 1)
        self.lcdNumber_39 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_39.setObjectName("lcdNumber_39")
        self.gridLayout.addWidget(self.lcdNumber_39, 4, 24, 1, 1)
        self.lcdNumber_40 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_40.setObjectName("lcdNumber_40")
        self.gridLayout.addWidget(self.lcdNumber_40, 5, 2, 1, 1)
        self.lcdNumber_43 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_43.setObjectName("lcdNumber_43")
        self.gridLayout.addWidget(self.lcdNumber_43, 5, 8, 1, 1)
        self.lcdNumber_44 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_44.setObjectName("lcdNumber_44")
        self.gridLayout.addWidget(self.lcdNumber_44, 5, 10, 1, 1)
        self.lcdNumber_45 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_45.setObjectName("lcdNumber_45")
        self.gridLayout.addWidget(self.lcdNumber_45, 5, 12, 1, 1)
        self.lcdNumber_46 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_46.setObjectName("lcdNumber_46")
        self.gridLayout.addWidget(self.lcdNumber_46, 5, 14, 1, 1)
        self.lcdNumber_47 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_47.setObjectName("lcdNumber_47")
        self.gridLayout.addWidget(self.lcdNumber_47, 5, 16, 1, 1)
        self.lcdNumber_48 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_48.setObjectName("lcdNumber_48")
        self.gridLayout.addWidget(self.lcdNumber_48, 5, 18, 1, 1)
        self.lcdNumber_49 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_49.setObjectName("lcdNumber_49")
        self.gridLayout.addWidget(self.lcdNumber_49, 5, 20, 1, 1)
        self.lcdNumber_50 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_50.setObjectName("lcdNumber_50")
        self.gridLayout.addWidget(self.lcdNumber_50, 5, 22, 1, 1)
        self.lcdNumber_51 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_51.setObjectName("lcdNumber_51")
        self.gridLayout.addWidget(self.lcdNumber_51, 5, 23, 1, 1)
        self.lcdNumber_52 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_52.setObjectName("lcdNumber_52")
        self.gridLayout.addWidget(self.lcdNumber_52, 5, 24, 1, 1)
        self.lcdNumber_53 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_53.setObjectName("lcdNumber_53")
        self.gridLayout.addWidget(self.lcdNumber_53, 6, 2, 1, 1)
        self.lcdNumber_54 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_54.setObjectName("lcdNumber_54")
        self.gridLayout.addWidget(self.lcdNumber_54, 6, 4, 1, 1)
        self.lcdNumber_55 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_55.setObjectName("lcdNumber_55")
        self.gridLayout.addWidget(self.lcdNumber_55, 6, 6, 1, 1)
        self.lcdNumber_56 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_56.setObjectName("lcdNumber_56")
        self.gridLayout.addWidget(self.lcdNumber_56, 6, 8, 1, 1)
        self.lcdNumber_57 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_57.setObjectName("lcdNumber_57")
        self.gridLayout.addWidget(self.lcdNumber_57, 6, 10, 1, 1)
        self.lcdNumber_58 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_58.setObjectName("lcdNumber_58")
        self.gridLayout.addWidget(self.lcdNumber_58, 6, 12, 1, 1)
        self.lcdNumber_59 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_59.setObjectName("lcdNumber_59")
        self.gridLayout.addWidget(self.lcdNumber_59, 6, 14, 1, 1)
        self.lcdNumber_60 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_60.setObjectName("lcdNumber_60")
        self.gridLayout.addWidget(self.lcdNumber_60, 6, 16, 1, 1)
        self.lcdNumber_61 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_61.setObjectName("lcdNumber_61")
        self.gridLayout.addWidget(self.lcdNumber_61, 6, 18, 1, 1)
        self.lcdNumber_62 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_62.setObjectName("lcdNumber_62")
        self.gridLayout.addWidget(self.lcdNumber_62, 6, 20, 1, 1)
        self.lcdNumber_63 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_63.setObjectName("lcdNumber_63")
        self.gridLayout.addWidget(self.lcdNumber_63, 6, 22, 1, 1)
        self.lcdNumber_64 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_64.setObjectName("lcdNumber_64")
        self.gridLayout.addWidget(self.lcdNumber_64, 6, 23, 1, 1)
        self.lcdNumber_65 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_65.setObjectName("lcdNumber_65")
        self.gridLayout.addWidget(self.lcdNumber_65, 6, 24, 1, 1)
        self.lcdNumber_66 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_66.setObjectName("lcdNumber_66")
        self.gridLayout.addWidget(self.lcdNumber_66, 7, 2, 1, 1)
        self.lcdNumber_67 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_67.setObjectName("lcdNumber_67")
        self.gridLayout.addWidget(self.lcdNumber_67, 7, 4, 1, 1)
        self.lcdNumber_68 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_68.setObjectName("lcdNumber_68")
        self.gridLayout.addWidget(self.lcdNumber_68, 7, 6, 1, 1)
        self.lcdNumber_69 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_69.setObjectName("lcdNumber_69")
        self.gridLayout.addWidget(self.lcdNumber_69, 7, 8, 1, 1)
        self.lcdNumber_70 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_70.setObjectName("lcdNumber_70")
        self.gridLayout.addWidget(self.lcdNumber_70, 7, 10, 1, 1)
        self.lcdNumber_71 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_71.setObjectName("lcdNumber_71")
        self.gridLayout.addWidget(self.lcdNumber_71, 7, 12, 1, 1)
        self.lcdNumber_72 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_72.setObjectName("lcdNumber_72")
        self.gridLayout.addWidget(self.lcdNumber_72, 7, 14, 1, 1)
        self.lcdNumber_73 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_73.setObjectName("lcdNumber_73")
        self.gridLayout.addWidget(self.lcdNumber_73, 7, 16, 1, 1)
        self.lcdNumber_74 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_74.setObjectName("lcdNumber_74")
        self.gridLayout.addWidget(self.lcdNumber_74, 7, 18, 1, 1)
        self.lcdNumber_75 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_75.setObjectName("lcdNumber_75")
        self.gridLayout.addWidget(self.lcdNumber_75, 7, 20, 1, 1)
        self.lcdNumber_76 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_76.setObjectName("lcdNumber_76")
        self.gridLayout.addWidget(self.lcdNumber_76, 7, 22, 1, 1)
        self.lcdNumber_77 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_77.setObjectName("lcdNumber_77")
        self.gridLayout.addWidget(self.lcdNumber_77, 7, 23, 1, 1)
        self.lcdNumber_78 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_78.setObjectName("lcdNumber_78")
        self.gridLayout.addWidget(self.lcdNumber_78, 7, 24, 1, 1)
        self.lcdNumber_79 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_79.setObjectName("lcdNumber_79")
        self.gridLayout.addWidget(self.lcdNumber_79, 8, 2, 1, 1)
        self.lcdNumber_80 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_80.setObjectName("lcdNumber_80")
        self.gridLayout.addWidget(self.lcdNumber_80, 8, 4, 1, 1)
        self.lcdNumber_81 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_81.setObjectName("lcdNumber_81")
        self.gridLayout.addWidget(self.lcdNumber_81, 8, 6, 1, 1)
        self.lcdNumber_82 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_82.setObjectName("lcdNumber_82")
        self.gridLayout.addWidget(self.lcdNumber_82, 8, 8, 1, 1)
        self.lcdNumber_83 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_83.setObjectName("lcdNumber_83")
        self.gridLayout.addWidget(self.lcdNumber_83, 8, 10, 1, 1)
        self.lcdNumber_84 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_84.setObjectName("lcdNumber_84")
        self.gridLayout.addWidget(self.lcdNumber_84, 8, 12, 1, 1)
        self.lcdNumber_85 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_85.setObjectName("lcdNumber_85")
        self.gridLayout.addWidget(self.lcdNumber_85, 8, 14, 1, 1)
        self.lcdNumber_86 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_86.setObjectName("lcdNumber_86")
        self.gridLayout.addWidget(self.lcdNumber_86, 8, 16, 1, 1)
        self.lcdNumber_87 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_87.setObjectName("lcdNumber_87")
        self.gridLayout.addWidget(self.lcdNumber_87, 8, 18, 1, 1)
        self.lcdNumber_88 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_88.setObjectName("lcdNumber_88")
        self.gridLayout.addWidget(self.lcdNumber_88, 8, 20, 1, 1)
        self.lcdNumber_104 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_104.setObjectName("lcdNumber_104")
        self.gridLayout.addWidget(self.lcdNumber_104, 9, 24, 1, 1)
        self.lcdNumber_89 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_89.setObjectName("lcdNumber_89")
        self.gridLayout.addWidget(self.lcdNumber_89, 8, 22, 1, 1)
        self.lcdNumber_90 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_90.setObjectName("lcdNumber_90")
        self.gridLayout.addWidget(self.lcdNumber_90, 8, 23, 1, 1)
        self.lcdNumber_91 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_91.setObjectName("lcdNumber_91")
        self.gridLayout.addWidget(self.lcdNumber_91, 8, 24, 1, 1)
        self.lcdNumber_92 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_92.setObjectName("lcdNumber_92")
        self.gridLayout.addWidget(self.lcdNumber_92, 9, 2, 1, 1)
        self.lcdNumber_93 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_93.setObjectName("lcdNumber_93")
        self.gridLayout.addWidget(self.lcdNumber_93, 9, 4, 1, 1)
        self.lcdNumber_94 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_94.setObjectName("lcdNumber_94")
        self.gridLayout.addWidget(self.lcdNumber_94, 9, 6, 1, 1)
        self.lcdNumber_95 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_95.setObjectName("lcdNumber_95")
        self.gridLayout.addWidget(self.lcdNumber_95, 9, 8, 1, 1)
        self.lcdNumber_96 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_96.setObjectName("lcdNumber_96")
        self.gridLayout.addWidget(self.lcdNumber_96, 9, 10, 1, 1)
        self.lcdNumber_97 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_97.setObjectName("lcdNumber_97")
        self.gridLayout.addWidget(self.lcdNumber_97, 9, 12, 1, 1)
        self.lcdNumber_98 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_98.setObjectName("lcdNumber_98")
        self.gridLayout.addWidget(self.lcdNumber_98, 9, 14, 1, 1)
        self.lcdNumber_99 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_99.setObjectName("lcdNumber_99")
        self.gridLayout.addWidget(self.lcdNumber_99, 9, 16, 1, 1)
        self.lcdNumber_100 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_100.setObjectName("lcdNumber_100")
        self.gridLayout.addWidget(self.lcdNumber_100, 9, 18, 1, 1)
        self.lcdNumber_101 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_101.setObjectName("lcdNumber_101")
        self.gridLayout.addWidget(self.lcdNumber_101, 9, 20, 1, 1)
        self.lcdNumber_102 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_102.setObjectName("lcdNumber_102")
        self.gridLayout.addWidget(self.lcdNumber_102, 9, 22, 1, 1)
        self.lcdNumber_103 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_103.setObjectName("lcdNumber_103")
        self.gridLayout.addWidget(self.lcdNumber_103, 9, 23, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1488, 26))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuRe = QtWidgets.QMenu(self.menubar)
        self.menuRe.setObjectName("menuRe")
        MainWindow.setMenuBar(self.menubar)
        self.actionReStart = QtWidgets.QAction(MainWindow)
        self.actionReStart.setObjectName("actionReStart")
        self.actionShutdown = QtWidgets.QAction(MainWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionlocal = QtWidgets.QAction(MainWindow)
        self.actionlocal.setObjectName("actionlocal")
        self.actionto_usb_stick = QtWidgets.QAction(MainWindow)
        self.actionto_usb_stick.setObjectName("actionto_usb_stick")
        self.actionFrom_1_salve_RPi = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi.setObjectName("actionFrom_1_salve_RPi")
        self.actionFrom_1_salve_RPi_2 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_2.setObjectName("actionFrom_1_salve_RPi_2")
        self.actionFrom_1_salve_RPi_3 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_3.setObjectName("actionFrom_1_salve_RPi_3")
        self.actionFrom_1_salve_RPi_4 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_4.setObjectName("actionFrom_1_salve_RPi_4")
        self.actionFrom_1_salve_RPi_5 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_5.setObjectName("actionFrom_1_salve_RPi_5")
        self.actionFrom_1_salve_RPi_6 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_6.setObjectName("actionFrom_1_salve_RPi_6")
        self.actionFrom_1_salve_RPi_7 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_7.setObjectName("actionFrom_1_salve_RPi_7")
        self.actionFrom_1_salve_RPi_8 = QtWidgets.QAction(MainWindow)
        self.actionFrom_1_salve_RPi_8.setObjectName("actionFrom_1_salve_RPi_8")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionEnd_Programm = QtWidgets.QAction(MainWindow)
        self.actionEnd_Programm.setObjectName("actionEnd_Programm")
        self.actionMinwindow = QtWidgets.QAction(MainWindow)
        self.actionMinwindow.setObjectName("actionMinwindow")
        self.menuSystem.addAction(self.actionReStart)
        self.menuSystem.addAction(self.actionShutdown)
        self.menuSystem.addSeparator()
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionEnd_Programm)
        self.menuSave.addAction(self.actionlocal)
        self.menuSave.addAction(self.actionto_usb_stick)
        self.menuRe.addAction(self.actionRefresh)
        self.menuRe.addAction(self.actionMinwindow)
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuRe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.salve_RPi1.setText(_translate("MainWindow", "1.salve_RPi"))
        self.Luftdrucksensor4.setText(_translate("MainWindow", "4.Sensor"))
        self.Luftdruck.setText(_translate("MainWindow", "Pressure/bar"))
        self.Temperatur.setText(_translate("MainWindow", "Temperature/°C"))
        self.salve_RPi8.setText(_translate("MainWindow", "8.salve_RPi"))
        self.salve_RPi6.setText(_translate("MainWindow", "6.salve_RPi"))
        self.salve_RPi4.setText(_translate("MainWindow", "4.salve_RPi"))
        self.salve_RPi2.setText(_translate("MainWindow", "2.salve_RPi"))
        self.salve_RPi7.setText(_translate("MainWindow", "7.salve_RPi"))
        self.Luftdrucksensor5.setText(_translate("MainWindow", "5.Sensor"))
        self.Luftdrucksensor1.setText(_translate("MainWindow", "1.Sensor"))
        self.Temperatursensor3.setText(_translate("MainWindow", "3.Sensor"))
        self.Temperatursensor2.setText(_translate("MainWindow", "2.Sensor"))
        self.Temperatursensor4.setText(_translate("MainWindow", "4.Sensor"))
        self.salve_RPi5.setText(_translate("MainWindow", "5.salve_RPi"))
        self.Temperatursensor5.setText(_translate("MainWindow", "5.Sensor"))
        self.salve_RPi3.setText(_translate("MainWindow", "3.salve_RPi"))
        self.Beschleunigung.setText(_translate("MainWindow", "Acceleration/m/s-2"))
        self.Luftdrucksensor2.setText(_translate("MainWindow", "2.Sensor"))
        self.Luftdrucksensor3.setText(_translate("MainWindow", "3.Sensor"))
        self.Temperatursensor1.setText(_translate("MainWindow", "1.Sensor"))
        self.label_2.setText(_translate("MainWindow", "Y-Richtung"))
        self.label.setText(_translate("MainWindow", "X-Richtung"))
        self.label_3.setText(_translate("MainWindow", "Z-Richtung"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuSave.setTitle(_translate("MainWindow", "Save data"))
        self.menuRe.setTitle(_translate("MainWindow", "Refresh"))
        self.actionReStart.setText(_translate("MainWindow", "ReStart"))
        self.actionShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.actionlocal.setText(_translate("MainWindow", "Locally"))
        self.actionto_usb_stick.setText(_translate("MainWindow", "to a usb stick"))
        self.actionFrom_1_salve_RPi.setText(_translate("MainWindow", "From 1.salve_RPi"))
        self.actionFrom_1_salve_RPi_2.setText(_translate("MainWindow", "From 2.salve_RPi"))
        self.actionFrom_1_salve_RPi_3.setText(_translate("MainWindow", "From 3.salve_RPi"))
        self.actionFrom_1_salve_RPi_4.setText(_translate("MainWindow", "From 4.salve_RPi"))
        self.actionFrom_1_salve_RPi_5.setText(_translate("MainWindow", "From 5.salve_RPi"))
        self.actionFrom_1_salve_RPi_6.setText(_translate("MainWindow", "From 6.salve_RPi"))
        self.actionFrom_1_salve_RPi_7.setText(_translate("MainWindow", "From 7.salve_RPi"))
        self.actionFrom_1_salve_RPi_8.setText(_translate("MainWindow", "From 8.salve_RPi"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionEnd_Programm.setText(_translate("MainWindow", "End Programm"))
        self.actionMinwindow.setText(_translate("MainWindow", "Minwindow"))

